### ISSUE TITLE
'train_data_joint.npy' file is missing

### ISSUE THREAD

**Issue by noirmist** [NetEase-GameAI/MoCap-Solver#5]
I'm trying to train your code. 
At the last evaluation step, I receive this missing file message.
And I can't find any code related with this except loading the file.

Could you explain more about this?
```
5. Start evaluate MoCap-Solver
MoCap_Solver/data/Testing_dataset/mocap_dataset
loading from models/mocap_solver.pth
load succeed!
model set up over!
Traceback (most recent call last):
  File "train_and_evaluate_MoCap_Solver.py", line 21, in <module>
    model_class.evaluate_solver()
  File "/workspace/MoCap-Solver/MoCap_Solver/MoCapSolver.py", line 68, in evaluate_solver
    evaluate_sequence()
  File "/workspace/MoCap-Solver/MoCap_Solver/evaluate/evaluate_sequence.py", line 32, in evaluate_sequence
    pd_class = PredictClass()
  File "/workspace/MoCap-Solver/MoCap_Solver/evaluate/predict.py", line 32, in __init__
    self.joint_data_statistic_data = np.load(self.jts_statistic_path)
  File "/opt/conda/envs/MoCapSolver/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'models/train_data_joint.npy'
```

Thanks

**Comment by Kirstihly** [comment]
I am able to find that file in MoCapSolver_pretrained.rar
